### ISSUE TITLE
/bin/sh: g16: command not found

### ISSUE THREAD

**Issue by dingweilu** [zadorlab/KinBot#61]
Hello everyone,
when I run the case in /examples/gvl_reactions, it returns error in "/bin/sh: g16: command not found", in our own computational environment, it provides a *.pbs template like following:
#! /bin/sh -x
#PBS -N uv_azo_trans_im_co2
#PBS -l nodes=1:ppn=52
#PBS -q batch
#PBS -j oe

### Modify the Gaussian gjf file name here! ###

GJF="uv_azo_trans_im_co2.gjf"

####################

export GAUSS_SCRDIR=/tmp
export g09root=/opt/gaussian

. $g09root/g09/bsd/g09.profile

cd $PBS_O_WORKDIR

JOBNAME=`basename "$GJF" .gjf`
$g09root/g09/g09 < $GJF > "$JOBNAME.log"

I'm confused how to built the g09root in *.json?

**Comment by juditzador** [comment]
Hi! Thanks for the question. Gaussian is called via ASE in KinBot, and the default version for the Gaussian calculator is g16:
[https://wiki.fysik.dtu.dk/ase/ase/calculators/gaussian.html](url)
So first, you need to add `"qc_command": "g09"` (if indeed `g09` is the command that leads to your Gaussian on your system).

I am also not sure what you mean by "in our own computational environment, it provides a *.pbs template like following". What is "it"? KinBot? This doesn't seem like our template. I also don't understand the line "Modify the Gaussian gjf file name here!" Is it in the file? 

Even more, I am confused as to why there is any reference to Gaussian in this template. The jobs that KinBot submits are python calculations, which are then internally, via ASE, call Gaussian. Maybe try running the example using the default (built-in) pbs template, and if they don't work because of specific settings you need, copy them, and start adding things you need. Here is more info: [https://github.com/zadorlab/KinBot/wiki/Input-and-Keywords#computational-environment](url)

Let me know if you run into further issues.
