### ISSUE TITLE
Reaction Mechanism 

### ISSUE THREAD

**Issue by BoomBangPow** [zadorlab/KinBot#77]
Hi,
I have several already calculated species from Gaussian. Is there a way to use them to derive the mechanism?
Thanks!

**Comment by juditzador** [comment]
Hi. It is not very easy at all to feed KinBot previously calculated structures. There are two reasons for that. First, the files are named in a particular way so that the code can recognize it follow alongs. Second, the atoms in each calculations need to be in the same order, and it might not be the case when you do things manually. Depending on how many species you have already, and how large your system is of course, but you might just give it a go to recalculate these things with KinBot and get to a nicely organized master equation. Your questions, however, is about mechanism. If you have all the structures (wells, saddles and bimolecular fragments) that you need, then there is no point running KinBot, those structures tell you the mechanism. Finally, if you want a nice visualization, you can use our PESViewer tool, it is certainly possible to create the input for that manually.

**Comment by BoomBangPow** [comment]
Thank you for your response. Is it possible to predict a reaction, if there are multiple components in a mixture?
How would formate the .json file then? Is there an example for it?
I'll try using PESViewer tool then.

**Comment by juditzador** [comment]
No, KinBot operates on a single PES, all the way to bimolecular fragments. It does not go further than that and it cannot predict reactions in mixtures. You'd have to run several KinBot calculations to explore chemistry of mixtures.
